name: 'Skip CI'
branding:
  icon: 'check-circle'
  color: 'white'
description: |
  'Allows users to skip the CI pipeline based on commit messages or file paths.'
inputs:
  github-token:
    description: 'GitHub authentiction token.'
    required: true
  excluded-paths:
    description: 'A list of paths that should be excluded from CI.'
    required: false
    default: '[]'
  stop-internally:
    description: 'Whether or not the action should stop the workflow itself.'
    required: false
    default: 'false'
outputs:
  stop-code:
    description: |
      The behaviour of the action:
      - `continue`
      - `cancel`
      - `skip`
      - `nothing`
      - `fail`
runs:
  using: 'node12'
  main: 'index.js'

