name: 'Skip CI'
branding:
  icon: 'check-circle'
  color: 'white'
description: |
  'Allows users to skip the CI pipeline based on commit messages or file paths.'
inputs:
  excluded-paths:
    description: 'A list of paths that should be excluded from CI.'
    required: false
    default: '[]'
  stop-internally:
    description: 'Whether or not the action should stop the workflow itself.'
    required: false
    default: 'false'
outputs:
  stop-code:
    description: 'The stop code: 0 - continue, 1 - cancel, 2 - skip, 3 - fail'
runs:
  using: 'node12'
  main: 'index.js'

