name: "Skip CI Action Test"

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

env:
  excludedPaths: |
    README.md
    LICENSE

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        run-id: ${{ github.run_id }}
        github-token: ${{ github.token }}
        excluded-paths: ${{ env.exludedPaths }}
        stop-internally: true
        skip-ci-message: '[skip ci]'

